spring.application.name=backend-Consoles

spring.jpa.properties.hibernate.jdbc.time_zone=UTC
spring.jpa.properties.hibernate.envers.audit_table_suffix=_aud
spring.jackson.serialization.fail-on-empty-beans=false
spring.flyway.enabled=true
spring.profiles.active=dev

logging.pattern.level=%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-},%X{usuario:-}]

management.endpoints.web.exposure.include=health,info,prometheus
management.tracing.sampling.probability=1.0

api.security.token.secret=${JWT_SECRET:1234}
