spring.datasource.url=jdbc:postgresql://${DB_HOST:localhost}:5432/backhistoriaconsoles
spring.datasource.username=${DB_USER:postgres}
spring.datasource.password=${DB_PASS:postgres}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=none
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

logging.level.root=INFO
logging.level.org.flywaydb.core=INFO
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.orm.results.loading=TRACE
logging.level.historia_consoles.backend_Consoles=DEBUG
