spring.datasource.url=jdbc:postgresql://${PROD_DB_HOST}:${PROD_DB_PORT:5432}/${PROD_DB_NAME}
spring.datasource.username=${PROD_DB_USER}
spring.datasource.password=${PROD_DB_PASS}

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=false

logging.level.root=INFO
logging.level.org.hibernate.SQL=ERROR
logging.level.historia_consoles.backend_Consoles=INFO
