CREATE TABLE public.console_aud (
    id bigint NOT NULL,
    rev bigint NOT NULL,
    revtype smallint,
    nome character varying(255),
    fabricante character varying(255),
    publicadora character varying(255),
    ativo boolean,
    descontinuado boolean,
    slug character varying(255),
    imagem_url character varying(255),
    unidades_vendidas character varying(255),
    geracao_id bigint,
    armazenamento character varying(255),
    console_tipo character varying(255),
    cpu character varying(255),
    gpu character varying(255),
    midia character varying(255),
    preco_lancamento character varying(255),
    ram character varying(255),
    resolucao character varying(255),
    inicio_periodo date,
    fim_periodo date,
    retrocompatibilidade boolean,
    CONSTRAINT console_aud_pkey PRIMARY KEY (id, rev),
    CONSTRAINT fk_console_aud_revinfo FOREIGN KEY (rev) REFERENCES public.revinfo(rev)
);
