ALTER TABLE jogos ADD COLUMN data_criacao TIMESTAMP WITHOUT TIME ZONE;
ALTER TABLE jogos ADD COLUMN data_ultima_modificacao TIMESTAMP WITHOUT TIME ZONE;
ALTER TABLE jogos ADD COLUMN criado_por VARCHAR(255);
ALTER TABLE jogos ADD COLUMN modificado_por VARCHAR(255);